version: '3.8'

services:
  ocr:
    image: ghcr.io/fzymgc-house/paperless-ngx-ocr2:latest
    container_name: paperless-ocr
    environment:
      # Set your Mistral AI API key here or via .env file
      - PAPERLESS_OCR_API_KEY=${MISTRAL_API_KEY:-your-api-key-here}
      - PAPERLESS_OCR_API_BASE_URL=${MISTRAL_API_BASE_URL:-https://api.mistral.ai}
      - PAPERLESS_OCR_TIMEOUT=${MISTRAL_TIMEOUT:-30}
      - PAPERLESS_OCR_MAX_FILE_SIZE_MB=${MISTRAL_MAX_FILE_SIZE_MB:-100}
      - PAPERLESS_OCR_LOG_LEVEL=${MISTRAL_LOG_LEVEL:-info}
    volumes:
      # Mount your documents directory
      - ./sample-files:/workspace
      # Mount config file if you have one
      - ./configs:/config:ro
    command: --file /workspace/sample.txt --verbose
    restart: "no"
    networks:
      - ocr-network

  # Example service for batch processing
  ocr-batch:
    image: ghcr.io/fzymgc-house/paperless-ngx-ocr2:latest
    container_name: paperless-ocr-batch
    environment:
      - PAPERLESS_OCR_API_KEY=${MISTRAL_API_KEY:-your-api-key-here}
      - PAPERLESS_OCR_API_BASE_URL=${MISTRAL_API_BASE_URL:-https://api.mistral.ai}
    volumes:
      - ./sample-files:/workspace
      - ./output:/output
    command: >
      sh -c "
        for file in /workspace/*.pdf /workspace/*.png /workspace/*.jpg; do
          if [ -f \"$file\" ]; then
            echo \"Processing: $file\"
            paperless-ngx-ocr2 --file \"$file\" --json > \"/output/$(basename \"$file\").json\"
          fi
        done
      "
    restart: "no"
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge

# Example .env file for this docker-compose.yml:
# MISTRAL_API_KEY=your-actual-api-key-here
# MISTRAL_API_BASE_URL=https://api.mistral.ai
# MISTRAL_TIMEOUT=30
# MISTRAL_MAX_FILE_SIZE_MB=100
# MISTRAL_LOG_LEVEL=info
