# Rustfmt configuration for paperless-ngx-ocr2
# Updated with current stable best practices and modern formatting standards

# Edition and basic settings
edition = "2021"
max_width = 160
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Code layout and formatting (stable features only)
use_small_heuristics = "Max"
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true

# Error handling and control flow
use_try_shorthand = true

# Imports (stable features only)
reorder_imports = true

# Function parameters (updated to use current option name)
fn_params_layout = "Tall"

# Miscellaneous
merge_derives = true
