# Cargo configuration for paperless-ngx-ocr2

[build]
# Target directory (can be overridden by environment)
# target-dir = "target"

[alias]
# Constitutional compliance aliases
lint = "clippy --all-targets --all-features -- -D warnings"
fmt-check = "fmt --all -- --check"
test-all = "test --all-features"

# Development convenience aliases  
check-all = "check --all-targets --all-features"
build-release = "build --release"
run-help = "run -- --help"

[target.'cfg(unix)']
# Unix-specific optimizations
rustflags = ["-C", "link-arg=-s"]

[profile.dev]
# Development profile optimizations
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256

[profile.test]
# Test profile settings
opt-level = 0
debug = 2
debug-assertions = true
overflow-checks = true
